name: Azure Static Web Apps CI/CD

on:
  # Manual trigger for Deploy to Azure button and user deployments
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: false
        default: 'production'
        type: choice
        options:
          - production
          - staging
      
  # Allow this workflow to be called by other workflows
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment'
        required: false
        default: 'production'
        type: string
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN:
        required: true
  
  # Push to specific branches (for your development workflow)
  push:
    branches:
      - deploy  # Only deploy when pushing to 'deploy' branch
      - release # Or release branch
    paths-ignore:
      - '**.md'  # Ignore documentation changes
      
  # Pull requests for preview deployments (optional)
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - deploy
      - release

jobs:
  build_and_deploy_job:
    if: |
      github.event_name == 'push' || 
      github.event_name == 'workflow_dispatch' || 
      github.event_name == 'workflow_call' ||
      (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment: ${{ inputs.environment || 'production' }}
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Configure Tenant ID in config files
        run: |
          # Get tenant ID from Azure context (this will be available during deployment)
          # For now, we'll use a placeholder that gets replaced by the configuration script
          echo "Configuration files use template placeholders that get replaced by configure-app.ps1"
          echo "Tenant ID will be configured during post-deployment setup"
        shell: bash
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
           script: |
               const coredemo = require('@actions/core')
               return await coredemo.getIDToken()
           result-encoding: string
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_SMOKE_0CD316503 || secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "out" # Built app content directory - optional
          github_id_token: ${{ steps.idtoken.outputs.result }}
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_SMOKE_0CD316503 || secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
